# Generated by Django 3.2.9 on 2021-11-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicInfo', '0001_initial'),
        ('faculty', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academicInfo.registration'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='students',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
