# Generated by Django 3.2.9 on 2021-11-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicInfo', '0003_alter_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default='Registration', max_length=100),
            preserve_default=False,
        ),
    ]
