# Generated by Django 3.2.9 on 2021-11-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_batch'),
        ('academicInfo', '0005_alter_registration_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
