# Generated by Django 3.2.9 on 2021-11-23 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicInfo', '0006_alter_courseregistration_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='semester',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
