# Generated by Django 3.2.9 on 2021-11-23 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicInfo', '0007_alter_courseregistration_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
