# Generated by Django 3.2.9 on 2021-11-24 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicInfo', '0008_alter_courseregistration_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 15, 45, 17, 241756)),
            preserve_default=False,
        ),
    ]
