# Generated by Django 3.2.9 on 2021-11-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.PositiveIntegerField(default=2021),
        ),
    ]
