name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.*]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Pinocchio/requirements.txt
    - name: Run migrations
      run: |
        python Pinocchio/manage.py makemigrations
        python Pinocchio/manage.py migrate
    - name: Run Tests
      run: |
        python Pinocchio/manage.py test account
